name: N64

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: configure
      run: |
        sudo apt install -y binutils-mips-linux-gnu build-essential git pkgconf python3
    - name: make
      run: |
        wget https://github.com/jb1361/Super-Mario-64-AI/blob/development/Super%20Mario%2064%20(USA).z64 baserom.us.z64
        make VERSION=us -j6
    - name: upload artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: sm64.z64
        path: build/us/sm64.us.z64
